export const options = [
  {
    label: 'Alaskan/Hawaiian Time Zone',
    data: {
      name: 'Alaskan/Hawaiian Time Zone',
    },
    options: [
      {
        value: 'AK',
        label: 'Alaska',
      },
      {
        value: 'HI',
        label: 'Hawaii',
      },
    ],
  },
  {
    id: 2,
    label: 'Pacific Time Zone',
    data: {
      name: 'Pacific Time Zone',
    },
    options: [
      { id: '2.1', value: 'CA', label: 'California' },
      { id: '2.2', value: 'NV', label: 'Nevada' },
      { id: '2.3', value: 'OR', label: 'Oregon' },
      { id: '2.4', value: 'WA', label: 'Washington' },
    ],
  },
  {
    label: 'Mountain Time Zone',
    data: {
      name: 'Mountain Time Zone',
    },
    options: [
      { value: 'AZ', label: 'Arizona' },
      { value: 'CO', label: 'valueado' },
      { value: 'ID', label: 'Idaho' },
      { value: 'MT', label: 'Montana' },
      { value: 'NE', label: 'Nebraska' },
      { value: 'NM', label: 'New Mexico' },
      { value: 'ND', label: 'North Dakota' },
      { value: 'UT', label: 'Utah' },
      { value: 'WY', label: 'Wyoming' },
    ],
  },
  {
    label: 'Central Time Zone',
    data: {
      name: 'Central Time Zone',
    },
    options: [
      { value: 'AL', label: 'Alabama' },
      { value: 'AR', label: 'Arkansas' },
      { value: 'IL', label: 'Illinois' },
      { value: 'IA', label: 'Iowa' },
      { value: 'KS', label: 'Kansas' },
      { value: 'KY', label: 'Kentucky' },
      { value: 'LA', label: 'Louisiana' },
      { value: 'MN', label: 'Minnesota' },
      { value: 'MS', label: 'Mississippi' },
      { value: 'MO', label: 'Missouri' },
      { value: 'OK', label: 'Oklahoma' },
      { value: 'SD', label: 'South Dakota' },
      { value: 'TX', label: 'Texas' },
      { value: 'TN', label: 'Tennessee' },
      { value: 'WI', label: 'Wisconsin' },
    ],
  },
]

export const STATES: string[] = [
  'Alabama',
  'Alaska',
  'American Samoa',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'District Of Columbia',
  'Federated States Of Micronesia',
  'Florida',
  'Georgia',
  'Guam',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Marshall Islands',
  'Maryland',
  'Massachusetts',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'Montana',
  'Nebraska',
  'Nevada',
  'New Hampshire',
  'New Jersey',
  'New Mexico',
  'New York',
  'North Carolina',
  'North Dakota',
  'Northern Mariana Islands',
  'Ohio',
  'Oklahoma',
  'Oregon',
  'Palau',
  'Pennsylvania',
  'Puerto Rico',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Tennessee',
  'Texas',
  'Utah',
  'Vermont',
  'Virgin Islands',
  'Virginia',
  'Washington',
  'West Virginia',
  'Wisconsin',
  'Wyoming',
]
